package com.ptda.tracker.models.tracker;

public enum BudgetActionType {

    CREATE_BUDGET,
    UPDATE_BUDGET,
    DELETE_BUDGET,

    CREATE_EXPENSE,
    UPDATE_EXPENSE,
    DELETE_EXPENSE,

    CREATE_BUDGET_ACCESS,
    UPDATE_BUDGET_ACCESS,
    DELETE_BUDGET_ACCESS,

    CREATE_EXPENSE_DIVISION,
    UPDATE_EXPENSE_DIVISION,
    DELETE_EXPENSE_DIVISION,

    CREATE_DISPUTE,
    UPDATE_DISPUTE,
    DELETE_DISPUTE

}
