spring:
  application:
    name: tracker
#  datasource:
#    url: jdbc:mysql://estga-dev.ua.pt:3306/PTDA24_BD_01
#    username: PTDA24_01
#    password: Xdft#345
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
     url: jdbc:mysql://localhost:3306/PTDA24_BD_01
     username: root
     password: Pass123!
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
      envers:
        audit_table_suffix: _AUDIT
        revision_field_name: rev
        revision_type_field_name: revtype
        store_data_at_delete: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: divi.expense.tracker@gmail.com
    password: yler fzep doct zqoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true